In [1]:
a = [[1,2,3],
     [0,5,6],
     [0,0,9]]

def det(mat,n):
    d = 0
    minus1 = 1
    if n==2:
        return mat[0][0]*mat[1][1] - mat[0][1]*mat[1][0]
    for i in range(n):
        red_mat = [[row[j] for j in range(n) if j!=i] for row in mat[1:]]
        d= d+ mat[0][i]*det(red_mat,n-1)*minus1
        minus1= minus1*-1
    return d

def adj(mat,n):
    minus1 = 1
    adjoint = [[0 for _ in range(n)] for _ in range(n)]
    for i in range(n):
        for j in range(n):
            red_mat = [[row[k] for k in range(n) if k!=j] for row in (mat[0:i]+mat[i+1:]) ]
            adjoint[j][i] = minus1*det(red_mat,n-1)
            minus1 = minus1*-1
    return adjoint



print(det(a,3))
adjoint1 = adj(a,3)
print(adjoint1)

import numpy as np
a1 = np.array(a)
adj1 = np.array(adjoint1)
print(np.dot(a,adjoint1))

#print([[row[i] for i in range(3) if i!=1] for row in a[1:]])

45
[[45, -18, -3], [0, 9, -6], [0, 0, 5]]
[[45  0  0]
 [ 0 45  0]
 [ 0  0 45]]
