In [1]:
import numpy as np
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]],dtype=float)
B = np.array([[8],[-11],[-3]],dtype=float)
print(A)
print(B)

[[ 2.  1. -1.]
 [-3. -1.  2.]
 [-2.  1.  2.]]
[[  8.]
 [-11.]
 [ -3.]]


In [2]:
def gaussian_elimination(matrix,vector):
    rows,cols = matrix.shape
    for col in range(cols):
        pivot_row = max(range(col,rows),key = lambda i: abs(matrix[i,col]))
        #print(pivot_row)
        matrix[[col,pivot_row]] = matrix[[pivot_row,col]]
        vector[[col,pivot_row]] = vector[[pivot_row,col]]
        #print(matrix)
        for row in range(col+1,rows):
            alpha = -matrix[row,col]/matrix[col,col]
            matrix[[row]]+=alpha*matrix[[col]]
            vector[[row]]+=alpha*vector[[col]]
            #print(matrix)  
    return matrix,vector

matrix = np.copy(A)
vector = np.copy(B)
np.set_printoptions(precision=2,suppress=True)
upper_tri,e_vector = gaussian_elimination(matrix,vector)
print(upper_tri)
print(e_vector)

[[-3.   -1.    2.  ]
 [ 0.    1.67  0.67]
 [ 0.    0.    0.2 ]]
[[-11.  ]
 [  4.33]
 [ -0.2 ]]


In [3]:
def back_substitution(matrix,vector):
    rows,cols =  matrix.shape
    x= np.zeros(cols)
    for i in range(cols-1,-1,-1):
        x[i] = (vector[i] - np.dot(matrix[i, i+1:],x[i+1:]))/matrix[i,i]
    return x
print(back_substitution(upper_tri,e_vector))

[ 2.  3. -1.]


C:\Users\khrithik\AppData\Local\Temp\ipykernel_13296\2011816407.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  x[i] = (vector[i] - np.dot(matrix[i, i+1:],x[i+1:]))/matrix[i,i]


In [4]:
# a = np.array([[22,23,38,45,57],
#     [6,7,8,9,10]],dtype=float)

# #a[[0]]=a[[0]]*2+a[[1]]*(-10)
# # print(a)
# print(a[:,1:2])

In [5]:
# for i in range(5,1,-1):
#     print(i)
# print(matrix[1:, 3:])
# print(np.zeros(3))
# print(np.dot([1,2,3],[1,2,3]))