In [18]:
import numpy as np
A = np.array([[2, 1, 1],
              [4, -6, 0],
              [-2, 7, 2]],dtype=float)
print(A)

[[ 2.  1.  1.]
 [ 4. -6.  0.]
 [-2.  7.  2.]]


In [30]:
def gaussian_elimination(matrix):
    rows,cols = matrix.shape
    identity=np.eye(rows)
    for col in range(cols):
        for row in range(col+1,rows):
            alpha = -matrix[row,col]/matrix[col,col]
            matrix[[row]]+=alpha*matrix[[col]]
            identity[[row]]+=alpha*identity[[col]]
            print(matrix)
            print(identity)
    for col in range(cols-1,0,-1):
        for row in range(col-1,-1,-1):
            alpha = -matrix[row,col]/matrix[col,col]
            matrix[[row]]+=alpha*matrix[[col]]
            identity[[row]]+=alpha*identity[[col]]
            print(matrix)
            print(identity)
    for row in range(rows):
        alpha=matrix[row,row]
        matrix[[row]]=matrix[[row]]/alpha
        identity[[row]]=identity[[row]]/alpha
    return matrix,identity
    
matrix = np.copy(A)
np.set_printoptions(precision=2,suppress=True)
diagonal_mat,e_identity = gaussian_elimination(matrix)
print(diagonal_mat)
print(e_identity)


[[ 2.  1.  1.]
 [ 0. -8. -2.]
 [-2.  7.  2.]]
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 0.  0.  1.]]
[[ 2.  1.  1.]
 [ 0. -8. -2.]
 [ 0.  8.  3.]]
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 1.  0.  1.]]
[[ 2.  1.  1.]
 [ 0. -8. -2.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [-1.  1.  1.]]
[[ 2.  1.  1.]
 [ 0. -8.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [-4.  3.  2.]
 [-1.  1.  1.]]
[[ 2.  1.  0.]
 [ 0. -8.  0.]
 [ 0.  0.  1.]]
[[ 2. -1. -1.]
 [-4.  3.  2.]
 [-1.  1.  1.]]
[[ 2.  0.  0.]
 [ 0. -8.  0.]
 [ 0.  0.  1.]]
[[ 1.5  -0.62 -0.75]
 [-4.    3.    2.  ]
 [-1.    1.    1.  ]]
[[ 1.  0.  0.]
 [-0.  1. -0.]
 [ 0.  0.  1.]]
[[ 0.75 -0.31 -0.38]
 [ 0.5  -0.38 -0.25]
 [-1.    1.    1.  ]]


In [29]:
print(np.dot(e_identity,A))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
